name: flowers_admin
version: 0.0.5
homepage: https://github.com/a-givertzman/flowers_admin
description: A new Flutter project.
# Prevent accidental publishing to pub.dev.
publish_to: 'none'

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  intl: ^0.20.2
  # window_manager: ^0.4.3
  window_size: ^0.1.0
  hmi_core:
    # path: ../hmi_core
    git:
      url: https://github.com/a-givertzman/hmi_core.git
      ref: 2.2.0
  ext_rw:
    # path: ../ext_rw
    git:
      url: https://github.com/a-givertzman/dart_ext_rw
      ref: 1.2.5
  uuid: ^4.5.1
  resizable_widget: ^1.0.5
  mask_text_input_formatter: ^2.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
  mockito: ^5.4.5
  flutter_lints: ^5.0.0
  # dart_code_metrics: ^5.7.6

flutter:
  uses-material-design: true
  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/settings/
